# Домашнє завдання №1 (Модуль 1. Знайомство з Data Science)

## Імпорт модулів

In [1]:
import numpy as np

## 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

Натура́льні чи́сла --- це числа, що виникають природним чином при лічбі. Це числа: $1$, $2$, $3$, $4$, $\ldots$ Множинунатуральних чисел прийнято позначати $\mathbb{N}$.

In [18]:
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


## 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.}

In [8]:
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 3. Створіть масив розміром $5\times 5$, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [9]:
random_matrix = np.random.randint(1, 11, (5, 5))
print(random_matrix)

[[ 8  8  4  7  3]
 [ 3  9  8  3  8]
 [ 3  8 10  9  5]
 [ 9  8  1  7 10]
 [10  5  4  8 10]]


## 4. Створіть масив розміром $4\times 4$, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [11]:
random_matrix = np.random.rand(4, 4)
print(random_matrix)

[[0.03576693 0.60571576 0.83872195 0.5334341 ]
 [0.62441843 0.24922794 0.83976534 0.53757368]
 [0.92958554 0.04994248 0.00099728 0.51892904]
 [0.88081891 0.65253583 0.02627556 0.9318627 ]]


## 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

### 5.1 Створення масивів

In [13]:
array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

print("Масив 1:", array1)
print("Масив 2:", array2)

Масив 1: [ 6  6 10  5  4]
Масив 2: [ 3  8  7 10  7]


### 5.2 Поелементні операції

In [15]:
# Виконаємо поелементну операцію додавання
addition_result = array1 + array2
print("Результат додавання:", addition_result)

# Виконаємо поелементну операцію віднімання
subtraction_result = array1 - array2
print("Результат віднімання:", subtraction_result)

# Виконаємо поелементну операцію множення
multiplication_result = array1 * array2
print("Результат множення:", multiplication_result)

Результат додавання: [ 9 14 17 15 11]
Результат віднімання: [ 3 -2  3 -5 -3]
Результат множення: [18 48 70 50 28]


## 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

Скалярний добуток (scalar or dot product) можна обчислити за наступною формулою $\vec v \cdot \vec u = v^1 u_1 + v^2 u_2 + v^3 u_3 + \ldots + v^n u_n$

In [20]:
vector1 = np.random.random(7)
vector2 = np.random.random(7)

scalar_product = np.dot(vector1, vector2)

print("Скалярний добуток векторів:", scalar_product)

Скалярний добуток векторів: 2.885423683537218


## 7. Створіть дві матриці розміром $2\times2$ та $2\times3$, заповніть їх випадковими цілими числами в діапазоні від $1$ до $10$ та перемножте їх між собою.

In [23]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("Результат множення:")
print(result)

Матриця 1:
[[ 2  9]
 [10  2]]
Матриця 2:
[[2 7 6]
 [3 7 8]]
Результат множення:
[[31 77 84]
 [26 84 76]]


## 8. Створіть матрицю розміром $3\times3$, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

Обсичлення оберненої матриці здійснюється за формулою:

$$ \mathrm{A}^{-1} = \frac{1}{\mathrm{det}(\mathrm{A})} \cdot \mathrm{adj}(\mathrm{A}), $$

де $ \mathrm{det}(A) $ --- визначник матриці $\mathrm A$, $\mathrm{adj}(\mathrm{A})$ --- доповнена матриця. 

Обернена матриця існує, якщо $ \mathrm{det}(A) \neq 0$. Матриця, для якої $ \mathrm{det}(A) = 0$ називається сингулярною, і для такої матриці оберненої не існує. Тому в коді ми маємо це перевірити.$


In [29]:
# Створимо матрицю розміром 3x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (3, 3))

# Виведемо початкову матрицю
print("Початкова матриця:")
print(matrix)

# Знайдемо обернену матрицю
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не має оберненої матриці, оскільки вона може бути сингулярною.")

Початкова матриця:
[[ 2  7  1]
 [ 2  9 10]
 [ 1  9  1]]
Обернена матриця:
[[ 0.83505155 -0.02061856 -0.62886598]
 [-0.08247423 -0.01030928  0.18556701]
 [-0.09278351  0.11340206 -0.04123711]]


## 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

Транспонована матриця $\mathrm{A}^T$, виникає з матриці $\mathrm{A}$  врезультаті заміни рядків нв стлвбчики $(\mathrm{A}^T)_{ji} = \mathrm{A}_{ij} $:

$$A = 
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
$$

Тоді транспонована матриця $ A^T $ буде мати вигляд:

$$
A^T = 
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6 \\
\end{bmatrix}
$$

In [30]:
matrix = np.random.rand(4, 4)

# Виведемо початкову матрицю
print("Початкова матриця:")
print(matrix)

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

# Виведемо транспоновану матрицю
print("Транспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[0.44274132 0.06546424 0.82839526 0.81316836]
 [0.58220939 0.80171671 0.25918519 0.3433177 ]
 [0.59601568 0.06345121 0.61408012 0.53233793]
 [0.35932785 0.89176065 0.61856193 0.71279955]]
Транспонована матриця:
[[0.44274132 0.58220939 0.59601568 0.35932785]
 [0.06546424 0.80171671 0.06345121 0.89176065]
 [0.82839526 0.25918519 0.61408012 0.61856193]
 [0.81316836 0.3433177  0.53233793 0.71279955]]


## 10. Створіть матрицю розміром $3\times4$ та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

$$
\mathbf{u} = \mathrm{A} \cdot \mathbf{v} = 
\begin{bmatrix}
  a_{11} & a_{12} & a_{13} \\
  a_{21} & a_{22} & a_{23} \\
  a_{31} & a_{32} & a_{33} \\
\end{bmatrix}
\begin{bmatrix}
  v_1 \\
  v_2 \\
  v_3 \\
\end{bmatrix}
=
\begin{bmatrix}
  a_{11} \cdot v_1 + a_{12} \cdot v_2 + a_{13} \cdot v_3 \\
  a_{21} \cdot v_1 + a_{22} \cdot v_2 + a_{23} \cdot v_3 \\
  a_{31} \cdot v_1 + a_{32} \cdot v_2 + a_{33} \cdot v_3 \\
\end{bmatrix}
$$


In [39]:
# Створимо матрицю розміром 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (3, 4))

# Створимо вектор розміром 4 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, 4)

# Виведемо матрицю і вектор
print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

# Перемножимо матрицю на вектор
result = np.dot(matrix, vector)

# Виведемо результат
print("Результат перемноження:")
print(result)

Матриця:
[[ 6  3  7 10]
 [ 8  1  7  5]
 [10  8  2  4]]
Вектор:
[ 8 10  5 10]
Результат перемноження:
[213 159 210]


## 11. Створіть матрицю розміром $2\times3$ та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [41]:
# Створимо матрицю розміром 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створимо вектор розміром 3 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(3)

# Виведемо матрицю і вектор
print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

# Перемножимо матрицю на вектор
result = np.dot(matrix, vector)

# Виведемо результат
print("Результат перемноження:")
print(result)

Матриця:
[[0.83520323 0.3536111  0.05206013]
 [0.33077744 0.73065574 0.38067504]]
Вектор:
[0.58731616 0.22167577 0.86382699]
Результат перемноження:
[0.61388631 0.68507699]


## 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

Поелементне множення двох матриць визначається так: результатом цієї операції є нова матриця, у якій кожний елемент результуючої матриці визначається, як добуток відповідних елементів вихідних матриць.

Елемент результуючої матриці $\mathrm C$ обчислюється як добуток відповідних елементів матриць $\mathrm A$ і $\mathrm B$:

$$
\mathrm C_{ij}  = \mathrm A_{ij} \cdot \mathrm B_{ij}
$$

де $\mathrm C_{ij}$ --- елемент результуючої матриці $\mathrm C$ на позиції $(i, j)$, $\mathrm A_{ij}$ --- елемент матриці $\mathrm A$ на позиції $(i, j)$ і $\mathrm B_{ij}$ - елемент матриці $\mathrm B$ на позиції $(i, j)$.

Поелементне множення відрізняється від стандартного множення матриць, оскільки в останньому випадку обчислюється добуток рядків однієї матриці на стовпці іншої матриці, що веде до іншої результуючої матриці.

In [42]:
# Створимо першу матрицю 2x2 з випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, (2, 2))

# Створимо другу матрицю 2x2 з випадковими цілими числами в діапазоні від 1 до 10
matrix2 = np.random.randint(1, 11, (2, 2))

# Виведемо обидві матриці
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

# Виконаємо поелементне множення матриць
result = np.multiply(matrix1, matrix2)

# Виведемо результат
print("Результат поелементного множення:")
print(result)

Перша матриця:
[[9 3]
 [3 9]]
Друга матриця:
[[2 1]
 [6 6]]
Результат поелементного множення:
[[18  3]
 [18 54]]


## 13. Створіть дві матриці розміром $2\times 2$, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

Добуток матриць визначаеться як:

$$\mathrm C_{ij} = \sum_{r=1}^m \mathrm A_{ir} \mathrm B_{rj} \;\;\; \left(i=1, 2, \ldots l;\; j=1, 2, \ldots n \right)$$

In [44]:
# Створимо першу матрицю 2x2 з випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, (2, 2))

# Створимо другу матрицю 2x2 з випадковими цілими числами в діапазоні від 1 до 10
matrix2 = np.random.randint(1, 11, (2, 2))

# Виведемо обидві матриці
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

# Знайдемо добуток матриць
result = np.dot(matrix1, matrix2)

# Виведемо результат
print("Результат добутку матриць:")
print(result)

Перша матриця:
[[10  5]
 [ 7  1]]
Друга матриця:
[[1 3]
 [7 5]]
Результат добутку матриць:
[[45 55]
 [14 26]]


## 14. Створіть матрицю розміром $5\times 5$, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [45]:
# Створимо матрицю 5x5 з випадковими цілими числами від 1 до 100
matrix = np.random.randint(1, 101, (5, 5))

# Виведемо матрицю
print("Матриця:")
print(matrix)

# Знайдемо суму елементів матриці
sum_of_elements = np.sum(matrix)

# Виведемо суму
print("Сума елементів матриці: ", sum_of_elements)

Матриця:
[[18 53 12 48 60]
 [17 74 57 66  1]
 [44 54  8  9 99]
 [11 91 90 30 69]
 [95 84 51  3 84]]
Сума елементів матриці:  1228


## 15. Створіть дві матриці розміром $4\times 4$, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

Віднімання матриць $\mathrm A - \mathrm B$ - це операція обчислення матриці $\mathrm C$ , усі елементи якої дорівнюють попарній різниці всіх відповідних елементів матриць $\mathrm A$ і $\mathrm B$, тобто фактичноце полементне віднімання.

In [47]:
# Створимо першу матрицю 4x4 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, (4, 4))

# Створимо другу матрицю 4x4 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, (4, 4))

# Виведемо обидві матриці
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

# Знайдемо різницю матриць
result = matrix1 - matrix2

# Виведемо результат
print("Різниця матриць:")
print(result)

Перша матриця:
[[2 2 3 1]
 [5 6 7 6]
 [6 1 2 5]
 [1 3 4 2]]
Друга матриця:
[[2 1 7 8]
 [8 5 9 5]
 [8 5 9 1]
 [3 4 9 2]]
Різниця матриць:
[[ 0  1 -4 -7]
 [-3  1 -2  1]
 [-2 -4 -7  4]
 [-2 -1 -5  0]]


## 16. Створіть матрицю розміром $3\times 3$, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [48]:
# Створимо матрицю 3x3 з випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.rand(3, 3)

# Виведемо матрицю
print("Матриця:")
print(matrix)

# Знайдемо суму елементів кожного рядка матриці та створимо вектор-стовпчик
sum_of_rows = np.sum(matrix, axis=1, keepdims=True)

# Виведемо вектор-стовпчик із сумами
print("Вектор-стовпчик із сумами рядків:")
print(sum_of_rows)

Матриця:
[[0.31111932 0.76970371 0.62060414]
 [0.59861073 0.99843358 0.23297765]
 [0.93019568 0.43345573 0.85539769]]
Вектор-стовпчик із сумами рядків:
[[1.70142718]
 [1.83002196]
 [2.2190491 ]]


## 17. Створіть матрицю розміром $3\times4$ з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [49]:
# Створимо матрицю 3x4 з довільними цілими числами (від -10 до 10)
matrix = np.random.randint(-10, 11, (3, 4))

# Виведемо початкову матрицю
print("Початкова матриця:")
print(matrix)

# Знайдемо матрицю з квадратами чисел
squared_matrix = np.square(matrix)

# Виведемо матрицю з квадратами чисел
print("Матриця з квадратами чисел:")
print(squared_matrix)

Початкова матриця:
[[  1  -5   1   3]
 [  1 -10  -5 -10]
 [  5   6   6  -2]]
Матриця з квадратами чисел:
[[  1  25   1   9]
 [  1 100  25 100]
 [ 25  36  36   4]]


## 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [52]:
# Створимо вектор розміром 4 з випадковими цілими числами від 1 до 50
vector = np.random.randint(1, 51, 4)

# Виведемо початковий вектор
print("Початковий вектор:", vector)

# Знайдемо вектор з квадратними коренями чисел
sqrt_vector = np.sqrt(vector)

# Виведемо вектор з квадратними коренями
print("Вектор з квадратними коренями чисел:", sqrt_vector)

Початковий вектор: [42 20 23 37]
Вектор з квадратними коренями чисел: [6.4807407  4.47213595 4.79583152 6.08276253]
